<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Product;

class BeautyProductsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $products = [
            // Skincare Products
            [
                'name' => 'Kem dưỡng ẩm chuyên sâu Hyaluronic Acid',
                'description' => 'Kem dưỡng ẩm chuyên sâu với Hyaluronic Acid giúp cấp ẩm tức thì và duy trì độ ẩm suốt 24h. Phù hợp cho mọi loại da, đặc biệt da khô và thiếu ẩm.',
                'price' => 450000,
                'category' => 'skincare',
                'brand' => 'BeautyAI',
                'sku' => 'SK001-HA',
                'stock' => 50,
                'skin_type' => 'dry',
                'age_group' => 'all',
                'ingredients' => 'Hyaluronic Acid, Glycerin, Ceramides, Vitamin E, Aloe Vera',
                'usage_instructions' => 'Thoa một lượng vừa đủ lên da sạch, massage nhẹ nhàng. Sử dụng 2 lần/ngày.',
                'shelf_life' => '24 tháng',
                'weight' => '50ml',
                'dimensions' => '5x5x8cm',
                'is_featured' => true,
                'is_active' => true,
            ],
            [
                'name' => 'Serum Vitamin C làm sáng da',
                'description' => 'Serum Vitamin C 20% giúp làm sáng da, giảm thâm nám và chống oxy hóa hiệu quả. Kết cấu mỏng nhẹ, thẩm thấu nhanh.',
                'price' => 380000,
                'category' => 'skincare',
                'brand' => 'BeautyAI',
                'sku' => 'SK002-VC',
                'stock' => 35,
                'skin_type' => 'normal',
                'age_group' => 'adult',
                'ingredients' => 'Vitamin C (L-Ascorbic Acid), Ferulic Acid, Vitamin E, Hyaluronic Acid',
                'usage_instructions' => 'Thoa 3-5 giọt lên da sạch vào buổi sáng. Luôn sử dụng kem chống nắng sau đó.',
                'shelf_life' => '12 tháng',
                'weight' => '30ml',
                'dimensions' => '3x3x10cm',
                'is_featured' => true,
                'is_active' => true,
            ],
            [
                'name' => 'Sữa rửa mặt gel kiểm soát bã nhờn',
                'description' => 'Sữa rửa mặt gel dịu nhẹ với Salicylic Acid giúp làm sạch sâu, kiểm soát bã nhờn và ngăn ngừa mụn. Phù hợp cho da dầu và hỗn hợp.',
                'price' => 280000,
                'category' => 'skincare',
                'brand' => 'BeautyAI',
                'sku' => 'SK003-SA',
                'stock' => 60,
                'skin_type' => 'oily',
                'age_group' => 'young',
                'ingredients' => 'Salicylic Acid, Tea Tree Oil, Niacinamide, Glycerin, Panthenol',
                'usage_instructions' => 'Làm ướt mặt, thoa một lượng nhỏ và massage nhẹ nhàng. Rửa sạch với nước.',
                'shelf_life' => '36 tháng',
                'weight' => '100ml',
                'dimensions' => '6x6x12cm',
                'is_featured' => false,
                'is_active' => true,
            ],
            [
                'name' => 'Kem chống nắng SPF 50+',
                'description' => 'Kem chống nắng phổ rộng SPF 50+ PA++++ bảo vệ da khỏi tia UVA/UVB. Kết cấu mỏng nhẹ, không gây nhờn rít.',
                'price' => 320000,
                'category' => 'skincare',
                'brand' => 'BeautyAI',
                'sku' => 'SK004-SPF',
                'stock' => 40,
                'skin_type' => 'all',
                'age_group' => 'all',
                'ingredients' => 'Zinc Oxide, Titanium Dioxide, Hyaluronic Acid, Vitamin E, Niacinamide',
                'usage_instructions' => 'Thoa đều lên mặt và cổ 15 phút trước khi ra ngoài. Thoa lại sau 2-3 giờ.',
                'shelf_life' => '24 tháng',
                'weight' => '50ml',
                'dimensions' => '5x5x8cm',
                'is_featured' => true,
                'is_active' => true,
            ],
            [
                'name' => 'Mặt nạ dưỡng ẩm chuyên sâu',
                'description' => 'Mặt nạ dưỡng ẩm với Hyaluronic Acid và Ceramides giúp cấp ẩm tức thì và phục hồi hàng rào bảo vệ da.',
                'price' => 150000,
                'category' => 'skincare',
                'brand' => 'BeautyAI',
                'sku' => 'SK005-MASK',
                'stock' => 80,
                'skin_type' => 'dry',
                'age_group' => 'all',
                'ingredients' => 'Hyaluronic Acid, Ceramides, Glycerin, Aloe Vera, Panthenol',
                'usage_instructions' => 'Đắp mặt nạ 15-20 phút, 2-3 lần/tuần. Rửa sạch với nước.',
                'shelf_life' => '24 tháng',
                'weight' => '25g',
                'dimensions' => '10x15cm',
                'is_featured' => false,
                'is_active' => true,
            ],

            // Makeup Products
            [
                'name' => 'Kem nền mỏng nhẹ long-lasting',
                'description' => 'Kem nền với công thức mỏng nhẹ, che phủ hoàn hảo và giữ màu suốt 12 giờ. Phù hợp mọi tone da.',
                'price' => 420000,
                'category' => 'makeup',
                'brand' => 'BeautyAI',
                'sku' => 'MK001-FDN',
                'stock' => 30,
                'skin_type' => 'all',
                'age_group' => 'all',
                'ingredients' => 'Dimethicone, Glycerin, Vitamin E, Hyaluronic Acid, SPF 15',
                'usage_instructions' => 'Thoa đều lên da đã dưỡng ẩm. Có thể build coverage theo ý muốn.',
                'shelf_life' => '24 tháng',
                'weight' => '30ml',
                'dimensions' => '4x4x10cm',
                'is_featured' => true,
                'is_active' => true,
            ],
            [
                'name' => 'Son môi lì không trôi màu',
                'description' => 'Son môi lì với công thức không trôi màu, giữ màu suốt 8 giờ. Bộ sưu tập 12 màu sắc đa dạng.',
                'price' => 280000,
                'category' => 'makeup',
                'brand' => 'BeautyAI',
                'sku' => 'MK002-LIP',
                'stock' => 45,
                'skin_type' => 'all',
                'age_group' => 'all',
                'ingredients' => 'Beeswax, Vitamin E, Shea Butter, Jojoba Oil',
                'usage_instructions' => 'Thoa trực tiếp lên môi. Có thể dùng cọ để tạo hiệu ứng gradient.',
                'shelf_life' => '36 tháng',
                'weight' => '3.5g',
                'dimensions' => '2x2x8cm',
                'is_featured' => false,
                'is_active' => true,
            ],
            [
                'name' => 'Phấn phủ kiềm dầu mịn màng',
                'description' => 'Phấn phủ với công thức kiềm dầu, giúp định hình lớp trang điểm và kiểm soát bã nhờn hiệu quả.',
                'price' => 250000,
                'category' => 'makeup',
                'brand' => 'BeautyAI',
                'sku' => 'MK003-POW',
                'stock' => 55,
                'skin_type' => 'oily',
                'age_group' => 'all',
                'ingredients' => 'Talc, Mica, Dimethicone, Vitamin E, Niacinamide',
                'usage_instructions' => 'Dùng cọ phấn thoa đều lên toàn bộ khuôn mặt sau khi trang điểm.',
                'shelf_life' => '36 tháng',
                'weight' => '10g',
                'dimensions' => '8x8x2cm',
                'is_featured' => false,
                'is_active' => true,
            ],

            // Perfume Products
            [
                'name' => 'Nước hoa nữ hương hoa hồng',
                'description' => 'Nước hoa nữ với hương thơm hoa hồng ngọt ngào, quyến rũ. Lưu hương lâu và tạo ấn tượng khó quên.',
                'price' => 850000,
                'category' => 'perfume',
                'brand' => 'BeautyAI',
                'sku' => 'PF001-ROS',
                'stock' => 25,
                'skin_type' => 'all',
                'age_group' => 'adult',
                'ingredients' => 'Rose Oil, Vanilla, Musk, Sandalwood, Jasmine',
                'usage_instructions' => 'Xịt lên cổ tay, cổ, sau tai. Tránh xịt trực tiếp lên quần áo.',
                'shelf_life' => '60 tháng',
                'weight' => '50ml',
                'dimensions' => '4x4x12cm',
                'is_featured' => true,
                'is_active' => true,
            ],
            [
                'name' => 'Nước hoa nam hương gỗ ấm',
                'description' => 'Nước hoa nam với hương gỗ ấm áp, nam tính. Phù hợp cho các dịp quan trọng và công việc.',
                'price' => 780000,
                'category' => 'perfume',
                'brand' => 'BeautyAI',
                'sku' => 'PF002-WOD',
                'stock' => 20,
                'skin_type' => 'all',
                'age_group' => 'adult',
                'ingredients' => 'Sandalwood, Cedar, Vanilla, Amber, Musk',
                'usage_instructions' => 'Xịt lên cổ tay, cổ, sau tai. Lưu hương 6-8 giờ.',
                'shelf_life' => '60 tháng',
                'weight' => '50ml',
                'dimensions' => '4x4x12cm',
                'is_featured' => false,
                'is_active' => true,
            ],

            // Haircare Products
            [
                'name' => 'Dầu gội phục hồi tóc hư tổn',
                'description' => 'Dầu gội chuyên phục hồi tóc hư tổn với Keratin và Argan Oil. Giúp tóc mềm mượt, bóng khỏe.',
                'price' => 320000,
                'category' => 'haircare',
                'brand' => 'BeautyAI',
                'sku' => 'HC001-SHP',
                'stock' => 40,
                'skin_type' => 'all',
                'age_group' => 'all',
                'ingredients' => 'Keratin, Argan Oil, Coconut Oil, Vitamin E, Panthenol',
                'usage_instructions' => 'Làm ướt tóc, thoa dầu gội và massage nhẹ nhàng. Rửa sạch với nước.',
                'shelf_life' => '36 tháng',
                'weight' => '250ml',
                'dimensions' => '8x8x15cm',
                'is_featured' => false,
                'is_active' => true,
            ],
            [
                'name' => 'Serum tóc chống rụng tóc',
                'description' => 'Serum tóc với Biotin và Niacinamide giúp giảm rụng tóc, kích thích mọc tóc mới và tăng cường sức khỏe tóc.',
                'price' => 380000,
                'category' => 'haircare',
                'brand' => 'BeautyAI',
                'sku' => 'HC002-SER',
                'stock' => 35,
                'skin_type' => 'all',
                'age_group' => 'adult',
                'ingredients' => 'Biotin, Niacinamide, Caffeine, Peppermint Oil, Rosemary Oil',
                'usage_instructions' => 'Thoa trực tiếp lên da đầu, massage nhẹ nhàng. Sử dụng 1-2 lần/ngày.',
                'shelf_life' => '24 tháng',
                'weight' => '60ml',
                'dimensions' => '4x4x12cm',
                'is_featured' => true,
                'is_active' => true,
            ],
        ];

        foreach ($products as $product) {
            Product::create($product);
        }

        $this->command->info('Đã tạo ' . count($products) . ' sản phẩm mỹ phẩm mẫu!');
    }
}
